### ISSUE TITLE
Chameleon Runner: Support properties on chameleon target 

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-container-chameleon#107]
##### Issue Overview

ChameleonTarget annotation only support properties (sys/env) on some attributes like `container`, `version` and `mode` but does not support properties on chameleon **value** (full string attribute).

##### Expected Behaviour
Support for:

```
ChameleonTarget("${arquillian.container}")
@RunWith(ArquillianChameleon.class)
public class GreetingServiceSystemPropertiesTest {
```

##### Current Behaviour
Bellow exception is raised:

```
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Value of Chameleon expression must be of form container:version:mode. For example wildfly:9.0.0.Final:managed. Refer to https://github.com/arquillian/arquillian-container-chameleon#supported-containers for the complete list of supported containers.
	at org.arquillian.container.chameleon.runner.ArquillianChameleon.run(ArquillianChameleon.java:44)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.IllegalArgumentException: Value of Chameleon expression must be of form container:version:mode. For example wildfly:9.0.0.Final:managed. Refer to https://github.com/arquillian/arquillian-container-chameleon#supported-containers for the complete list of supported containers.
	at org.arquillian.container.chameleon.runner.ChameleonTargetConfiguration.<init>(ChameleonTargetConfiguration.java:35)
	at org.arquillian.container.chameleon.runner.ChameleonTargetConfiguration.from(ChameleonTargetConfiguration.java:64)
```

**Comment by rmpestano** [comment]
This was fixed by #108
