### ISSUE TITLE
jbossHome is missing slashes using windows

### ISSUE THREAD

**Issue by CSchulz** [arquillian/arquillian-container-chameleon#19]
Hello,

I have tried to set up my first project and got following exception. The folder exists if you add the directory seperator. But it seems to get lost under windows.

My arquillian.xml just contains the target.

```
Caused by: org.jboss.arquillian.container.spi.ConfigurationException: jbossHome 'C:businesstargetserverwildfly-dist_8.2.0.Finalwildfly-8.2.0.Final' must exist
        at org.jboss.arquillian.container.spi.client.deployment.Validate.configurationDirectoryExists(Validate.java:139)
        at org.jboss.as.arquillian.container.DistributionContainerConfiguration.validate(DistributionContainerConfiguration.java:99)
        at org.jboss.as.arquillian.container.managed.ManagedContainerConfiguration.validate(ManagedContainerConfiguration.java:73)
        at org.jboss.arquillian.container.impl.ContainerImpl.createDeployableConfiguration(ContainerImpl.java:115)
        at org.jboss.arquillian.container.impl.ContainerImpl.setup(ContainerImpl.java:181)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$7.perform(ContainerLifecycleController.java:149)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$7.perform(ContainerLifecycleController.java:145)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
```

**Comment by aslakknutsen** [comment]
Hmm, not sure why this would happen. 

The value should be resolved from here:
https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/controller/DistributionController.java#L67

And set on this object and validated here:
https://github.com/wildfly/wildfly-arquillian/blob/master/common/src/main/java/org/jboss/as/arquillian/container/DistributionContainerConfiguration.java#L100

I currently don't have access to a Windows machine, but if you would be willing to debug this I'm happy to help/guide/fix it. :+1:

**Comment by CSchulz** [comment]
I have summarized the failsafe plugin execution http://pastebin.com/4KAuDwsX 

If you have more details how I can deliver more debug information, tell me please.

**Comment by sfcoy** [comment]
@CSchulz are you setting jbossHome in Java like this:

       String jbossHome = "C:\business\target\server\wildfly-dist_8.2.0.Final\wildfly-8.2.0.Final";
       ...
       // configure arquillian with jbossHome
       ...

?

All those single backslashes will disappear because they behave as escape characters. You need to double them up:

      String jbossHome = "C:\\business\\target\\server\\wildfly-dist_8.2.0.Final\\wildfly-8.2.0.Final";

**Comment by aslakknutsen** [comment]
@sfcoy To my understanding he only defines the chameleonTarget configuration to 'something' managed, so chameleon should extract the dist zip into some folder and set the jbossHome automatically. The extraction is done here https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/controller/DistributionController.java#L67 and the setting of the variable is here  https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/controller/DistributionController.java#L87

All that is File/String stuff in so with out debugging the running code i'm not sure where the slashes are removed.

**Comment by CSchulz** [comment]
@aslakknutsen is correct.

Can you give me some details how to debug your extension? I am not sure how to trigger the invocation of Chameleon over Eclipse/IntelliJ/etc.

**Comment by CSchulz** [comment]
DistributionController.updateTargetConfiguration:

values: `"dist" -> "C:\...\target\server\wildfly-dist_8.2.0.Final\wildfly-8.2.0.Final"`

ContainerDefImpl.overrideProperty updates the configuration and the backslashes are lost.
